### ISSUE TITLE
Backend to-do

### ISSUE THREAD

**Issue by Hanif-adedotun** [Startvest/interna#45]
- [ ] Create User Model
- [ ] Create Profile Model
- [ ] Create Post Model
- [ ] Create Comment Model
- [ ] Authentication of users
- [ ] Set up Firebase account, then api for object storage for user profiles
